# Generated by Django 5.2.9 on 2025-12-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=200)),
                ('openingHours', models.CharField(max_length=200)),
                ('avgStayMinutes', models.IntegerField()),
                ('priceLevel', models.IntegerField()),
                ('rating', models.FloatField()),
                ('wineTags', models.CharField(max_length=200)),
                ('experienceTags', models.CharField(max_length=200)),
                ('avgTastingPricePerPerson', models.IntegerField()),
                ('avgMealPricePerPerson', models.IntegerField()),
                ('avgBottlePrice', models.IntegerField()),
                ('site', models.CharField(max_length=200)),
                ('contacts', models.CharField(max_length=200)),
            ],
        ),
    ]
