# Generated by Django 5.2.9 on 2025-12-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('location_id',), name='uniq_location_id_not_deleted'),
        ),
    ]
